# Generated by Django 4.2 on 2023-05-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_customuser_birth_date_alter_customuser_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_image",
            field=models.ImageField(blank=True, null=True, upload_to="static/images"),
        ),
    ]
