# Generated by Django 4.2 on 2023-05-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_remove_customuser_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_image",
            field=models.ImageField(
                blank=True,
                default="static/images/Screenshot_2023-05-07_121816.png",
                null=True,
                upload_to="static/images",
            ),
        ),
    ]
