# Generated by Django 4.2 on 2023-05-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_customuser_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_image",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
