# Generated by Django 4.2 on 2023-05-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_payment_current_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.FloatField(null=True),
        ),
    ]
