# Generated by Django 4.2 on 2023-05-11 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_alter_payment_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="amount",
            new_name="input_amount",
        ),
    ]
