# Generated by Django 4.2 on 2023-05-11 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0005_rename_amount_payment_input_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="current_amount",
        ),
    ]
