# Generated by Django 4.2 on 2023-05-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_feedback_remove_rate_project_remove_rate_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="created_dt",
            field=models.DateField(auto_now_add=True),
        ),
    ]
