# Generated by Django 4.2 on 2023-04-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("details", models.TextField()),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField()),
                ("created_dt", models.DateTimeField(auto_now_add=True)),
                ("tags", models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
    ]
