# Generated by Django 4.2 on 2023-05-07 01:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Rate",
        ),
    ]
