# Generated by Django 4.2 on 2023-04-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
