# Generated by Django 4.2 on 2023-05-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_delete_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="current_amount",
            field=models.IntegerField(default=0),
        ),
    ]
