# Generated by Django 4.2 on 2023-04-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_project_category_alter_project_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="target_amount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
