# Generated by Django 4.2 on 2023-05-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_project_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thumbnail",
            name="image",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
