# Generated by Django 4.2 on 2023-04-30 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_project_target_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="target_amount",
        ),
    ]
