# Generated by Django 4.2 on 2023-04-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_remove_project_target_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="target_amount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
