# Generated by Django 4.2 on 2023-05-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_thumbnail_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
