# Generated by Django 4.2 on 2023-05-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_alter_project_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("Health", "Health"),
                    ("Education", "Education"),
                    ("Environment", "Environment"),
                    ("Animals", "Animals"),
                    ("Culture & Art", "Culture & Art"),
                    ("Other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
