# Generated by Django 4.2 on 2023-05-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_project_image_delete_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
